#!/usr/bin/env bash

if [ -z "${FLAG}" ]; then
    >&2 echo "Error: FLAG variable is not set or is empty."
    exit 1
fi

echo "NOTE FOR EDDIE: This code errors when localhost calls it as it's not a valid country, it's serving on flask defaults atm"

cd src
pip install -r requirements.txt
flask --app main run
